name: Deploy EWB-UTK Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Build website
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ewb-utk-website-dist
        path: dist/
        retention-days: 30
        
    # Optional: Deploy to GitHub Pages for preview
    - name: Deploy to GitHub Pages (Preview)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
    # UTK Deployment (when SSH access is available)
    - name: Deploy to UTK Server
      if: github.ref == 'refs/heads/main'
      env:
        UTK_HOST: linux.oit.utk.edu
        UTK_USERNAME: ${{ secrets.UTK_USERNAME }}
        UTK_PRIVATE_KEY: ${{ secrets.UTK_PRIVATE_KEY }}
      run: |
        # Install SSH client
        sudo apt-get update
        sudo apt-get install -y openssh-client
        
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$UTK_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $UTK_HOST >> ~/.ssh/known_hosts
        
        # Upload files to UTK server
        echo "Uploading to UTK server..."
        scp -r dist/* $UTK_USERNAME@$UTK_HOST:~/public_html/
        
        # Set correct permissions
        ssh $UTK_USERNAME@$UTK_HOST "chmod 755 ~/public_html && chmod 644 ~/public_html/* && chmod 755 ~/public_html/assets && chmod 644 ~/public_html/assets/*"
        
        echo "✅ Deployment complete!"
      if: false  # Disabled by default - enable when UTK credentials are set up
